name: time_tracker
description: Um app simples para rastrear o tempo gasto em alguma atividade.

version: "0.1.1"

repository: "https://github.com/israelss/time_tracker"
issue_tracker: "https://github.com/israelss/time_tracker/issues"

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+2
  flutter_modular: ^0.5.3
  flutter:
    sdk: flutter
  dartz: ^0.8.9
  get: ^1.11.1
  velocity_x: ^0.1.1

dev_dependencies:
  hive_generator: ^0.7.0+2
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

scripts:
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  build: flutter pub run build_runner build --delete-conflicting-outputs
  clean: flutter pub run build_runner clean
  build_icons: flutter pub run flutter_launcher_icons:main
  release: flutter build apk --release --target-platform android-arm64

flutter:
  uses-material-design: true
